# fly.toml app configuration file generated for noosphere on 2026-02-26T12:54:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noosphere'
primary_region = 'ams'

[build]

[env]
  HOST = '0.0.0.0'
  PORT = '3000'
  DB_PATH = '/app/data/noosphere.db'

[[mounts]]
  source = 'noosphere_data'
  destination = '/app/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
